### ISSUE TITLE
Feedback: Thank you for creating this, is the perfect tool for uni calculations! ❤️

### ISSUE THREAD

**Issue by KierPrev** [bornova/numara-calculator#11]
I was using Jupyter notebook for my physics calculations, but this tool makes it simpler and faster to write everything!

It is excellent as it is, maybe the only thing that I would add, would be physics constants, like c, h, electron_mass, etc, but I'm loving that it has unit conversions, I already tried with eV to Joules.

Thanks!

**Comment by bornova** [comment]
Hi @KierPrev,
Thanks for the feedback!  All constants and units are provided by the [math.js](https://mathjs.org/docs/datatypes/units.html) library.  It already includes an extensive list of constants, including `electronMass` ([full list here](https://mathjs.org/docs/datatypes/units.html#physical-constants)).

In order to avoid clashes with math.js, I have decided not to include my own defined constants.  However, if you really need to, you can define your own constants in Numara's 'User functions and units' option. For example, you can define speed of light constant `c` as a unit:
<img src="https://user-images.githubusercontent.com/35872220/191414370-4826e97a-3ca2-4d4f-8f0a-50abd30caf54.png" width="600">
You can then do:
<img src="https://user-images.githubusercontent.com/35872220/191414746-8e43d43e-8942-4ff6-8dae-cb860cd1a69f.png" width="600">
Note: Your feedback has also led me to find a small bug which I have fixed in v3.16.0 so I recommend upgrading to this version.  It's not perfect and there is room for improvement but hope this helps.  Thanks again for your feedback and please let me know if you have any questions!

**Comment by KierPrev** [comment]
Thank you! I didn't know that this had mathjs constants.
Haha yeah, I noticed that little units bug, thanks for the fix :)
