### ISSUE TITLE
Treat comma as decimal sign

### ISSUE THREAD

**Issue by Reyhn3** [bornova/numara-calculator#13]
For international users, it would be great if comma ',' could be interpreted as a decimal sign.
Either as a setting (select comma or period), or automatically treat both comma and period as a decimal sign.

**Comment by bornova** [comment]
Hi @Reyhn3,
You can switch to a different locale, in Settings, where commas are used as decimal separators.  Ex. If you pick Turkish, you can do `1,1 + 1,2` with an answer of `2,3`.  However, keep in mind you would also need to switch to semi-colons as argument separators.  Ex. Instead of `sum(1.1, 1.2)` you would need to do `sum(1,1; 1,2)` to get the right answer.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/35872220/204115443-f2dd5c78-117b-4a1d-a6e9-1cff7aadbc00.png">

Again, sorry about the lack of documentation of things like these.  I plan on creating some docs soon.

**Comment by Reyhn3** [comment]
Ah, now that you mention it, it makes total sense! Except for the heading "Date & Time". 😄  Yes, documentation would have helped 😉 

But, instead of "locale" and the options already present... Is there a better way to communicate that this affects also commas and separators? I don't know, but I guess there would be an ISO-standard for this kind of stuff. The locale options would probably be more semantic in that case, as opposed to choosing between "English (UK)" and "English (US)" etc.

**Comment by bornova** [comment]
Locale setting at the earlier stages would only change the way dates were displayed, so you could choose to display `today` as either 11/27/2022 or 27/11/2022 depending on your locale.  And once comma decimal separator was introduced, I just kept it in the same 'Locale' setting under 'Date & Time'. 

When you choose a locale that uses commas as decimal separators, there is a small warning icon that shows up:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/35872220/204149031-951d6cf2-5262-4c8e-9e48-f6ec6d825446.png">
And if you click on the warning icon, it will show you the warning in detail:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/35872220/204149074-00ca35c4-6150-4c0f-9d00-4dceae0a6935.png">
There is an ISO language code for each language/country but I only chose to include most common ones for simplicity :smile: Thanks for the feedback!

**Comment by bornova** [comment]
Closing this for now.  Please let me know if you have any other issues.
