### ISSUE TITLE
Ability to toggle comma in result copy

### ISSUE THREAD

**Issue by vzeazy** [bornova/numara-calculator#15]
Great app. Beats the rest on Windows in terms of appearance and simplify. Thank you! :)

Used Qalculate prior and the ability to have different settings for the comma/thousands-separator between appearance and copy was great. Many financial apps complain when a comma is present in the pasted value. Yet, it's great to have it visually in the calculator.

**Comment by bornova** [comment]
Hi @vzeazy!
Thanks for the feedback.  I think it is a great idea.  It sure is annoying sometimes to copy the result with thousands separator and have issues where you paste it.  I will add the option to copy without the separator in the next release.

**Comment by bornova** [comment]
Hi @vzeazy,
The option to include or exclude the comma separator in copied answer can now be found in Settings.  The default behavior is not to include the separator.  Thank you for the suggestion!

<img width="502" alt="image" src="https://user-images.githubusercontent.com/35872220/212460011-b8672c71-fe81-49a9-a4a4-5383036f6033.png">

**Comment by vzeazy** [comment]
Thank you sir. That was an insanely fast update!

Not sure if it makes sense to add, but perhaps the reverse functionality would be nice as well. When pasting in from somewhere that has a separator, to either ignore it or auto-remove. Currently it seems to just choke up on it and require manual formatting.

**Comment by bornova** [comment]
Hi @vzeazy,
Removing the separator from the paste operation would be a bit more complex I am afraid.  Not because it is very difficult to implement but may not be as user friendly.  Numara allows you to use many built in functions which use commas and removing separators, such as commas, may cause confusion.  For example, if you pasted `sum(1,200)`, the expected result would be `201` but if we removed the comma, the result would be `1,200`.  Basically, how would we differentiate between pasting `1 comma 200` vs `1200`?  Also, some locales use commas as decimal separators (ex. Turkish) so `sum(1,200)` in that case would produce `1,2` which is `1.2` in en-us.

I think it's better to keep it as is for the paste operation. 😄 What do you think?

**Comment by bornova** [comment]
Closing this issue for now.  I can re-open if needed.  Thank you!

**Comment by vzeazy** [comment]
Thanks. Sounds good. Not sure what happened, but wrote a big message earlier and it didn't seem to send through. 

Yeah, completely understand and actually thought the variability of the thousands separator based on locale may cause some difficulties. Didn't even know about the built-in functions yet, super handy! 

Thanks again and the wonderful app.
My main calculator on Windows (still using Numi on Mac - just out of habit).
