### ISSUE TITLE
Numara.app takes too much time to launch on Mac OS.

### ISSUE THREAD

**Issue by cvzakharchenko** [bornova/numara-calculator#16]
I have MacBook Pro M1 Pro and Numara takes far longer to launch than any alternative.
Maybe around 5 seconds.

**Comment by bornova** [comment]
Hi @cvzakharchenko!
Thank you for the feedback.  Currently there is no build available for arm64 devices such as the M1 machine you have.  I am now thinking maybe there should be.  The performance difference maybe due to the architecture of the builds.  I still use an older Intel based MacBook Pro and don't have this issue.  I just added an arm64 build to the releases and maybe you can help me test this theory.  Would you mind uninstalling Numara and reinstalling the new [Numara-3.18.0-arm64.dmg](https://github.com/bornova/numara-calculator/releases/download/v3.18.0/Numara-3.18.0-arm64.dmg) please?  And let me know if the startup time is improved or not?

**Comment by cvzakharchenko** [comment]
@bornova Just updated and checked.
Now it starts in about 1 second.
Perfect! Thanks for a quick fix!

**Comment by bornova** [comment]
@cvzakharchenko
No problem!  Glad that solved the issue.  I should have released an ARM version sooner. Thanks for bringing it up! 

Ok to close this issue?

**Comment by cvzakharchenko** [comment]
@bornova Sure, the issue can be closed now.
