### ISSUE TITLE
Circling through history

### ISSUE THREAD

**Issue by 1andro1** [bornova/numara-calculator#20]
Hello,

would it be possible when the cursor is in a new line ctrl+up/down arrows to circle through entered history?

I also noticed that when the cursor is in new line and the new line starts with arithmetic sign the program performs the operation instead of issuing error:

![image](https://user-images.githubusercontent.com/79647326/230466178-61f73030-ce09-42e2-831a-e3b4c80ecb84.png)

Is that intentional?

Best Regards,
Adriyan

**Comment by bornova** [comment]
Hi @1andro1!
Cycling thru the history is an interesting idea!  I like it.  I will look into implementing that in an upcoming release.

The continuation of the calculation from previous line is by design and is enabled by default but this can be turned off in settings:

![Untitled](https://user-images.githubusercontent.com/35872220/230494449-3bf2bd7a-1e96-420f-9982-27db420bfa44.png)

Thanks for the feedback!

**Comment by 1andro1** [comment]
I understand it now! Many thanks!
