### ISSUE TITLE
totals calculate wrong result

### ISSUE THREAD

**Issue by johannesjh** [bornova/numara-calculator#3]
hi, not sure what is going on here... totals calculate a false result. maybe because negative numbers are not taken into account correctly? (see attached screenshot) thx Johannes

![Screenshot from 2021-07-26 15-58-54](https://user-images.githubusercontent.com/581188/127001413-7ea30929-880f-42cc-abf7-e0cb597b260b.png)

tested in numara 3.4.2

**Comment by bornova** [comment]
Hi @johannesjh,
The `total` keyword calculates the total of all answers, not the inputs.  Also, a line starting with an operator (+, -, /, *) continues the calculation from the previous line.  In order to get the result you are looking for, you can separate the inputs by an empty line like this:

![numara](https://user-images.githubusercontent.com/35872220/128103280-025624a7-7a9f-46f2-8de0-10ec26448082.png)

Thank you for reporting!

**Comment by johannesjh** [comment]
oh, alright. thank you for the clarification!
