### ISSUE TITLE
Probably a bug

### ISSUE THREAD

**Issue by 1andro1** [bornova/numara-calculator#36]
Hello,

I am trying to calculate the following line the the calculator gives me as answer 0:

1/(4*3.14*3.14*9e-6*300e3*300e3)

![Numara_njJENeDKDx](https://github.com/bornova/numara-calculator/assets/79647326/f44fe758-e696-4bb7-bfe1-4e1634e5792c)

Best Regards,
Adriyan

**Comment by bornova** [comment]
Hi Adriyan,
That's because the answer is so small that it is being rounded down to 0.  Please try to increase the precision in settings to allow more decimal points.  Here is the result with precision of 16 (max value allowed at the moment):

![image](https://github.com/bornova/numara-calculator/assets/35872220/dd4ada80-e7ce-48e6-bd18-cdf4e7903505)


![image](https://github.com/bornova/numara-calculator/assets/35872220/e3383b33-7c76-4ada-9936-bafafa374b9d)

**Comment by 1andro1** [comment]
Hello,

you are correct. It seems that after the update the Upper/Lower exponent limits were set to the default value of 12 and I never paid attention to them. My problem is from there. With values set to 4 everything is ok. 

Many thanks for your answer!

Best Regards,
Adriyan
