### ISSUE TITLE
Unexpected return value

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#37]
![QQ截图20240124164953](https://github.com/bornova/numara-calculator/assets/13564117/94b52dc2-2c81-4fdf-ac2e-d06edf7e6011)

https://github.com/bornova/numara-calculator/assets/13564117/bde23283-4255-4b03-a450-085a2c66162d

Numara does not support 64-bit data types; is that correct?

**Comment by bornova** [comment]
Hi @gagmeng,
Yes, I believe 64-bit data puts the answer out of range of the calculator so it may give unexpected results.  However, converting the decimal value to a [BigNumber](https://mathjs.org/docs/datatypes/bignumbers.html) first would fix the problem.  You can try:
```javascript
format(bignumber('-830'), {notation: "hex", wordSize: 64})  // 0xfffffffffffffcc2i64
```

Similar issue with the second part of your questions.  Numbers greater than 15 significant digits would need to be converted to `bignumber` first. Here is an example:
```javascript
hex(bignumber('18446744073709550') + 2931)  // 0x4189374bc6b361
hex(bignumber('18446744073709551') + 2931)  // 0x4189374bc6b362
hex(bignumber('18446744073709552') + 2931)  // 0x4189374bc6b363
hex(bignumber('18446744073709553') + 2931)  // 0x4189374bc6b364
```

On that note, I did find that using a number instead of string value in `bignumber` function gives incorrect result:
```javascript
hex(bignumber(18446744073709551) + 2931)  // 0x4189374bc6b361
hex(bignumber('18446744073709551') + 2931)  // 0x4189374bc6b362
```
This may be a bug with [Math.js](https://github.com/josdejong/mathjs) and I will report it there.

Thank you!

**Comment by bornova** [comment]
I posted the question [here](https://github.com/josdejong/mathjs/issues/3137) and looks like it has to do with the rounding errors when it comes to javascript handling large numbers.

**Comment by gagmeng** [comment]
![QQ截图20240125105028](https://github.com/bornova/numara-calculator/assets/13564117/1e88d15f-ea77-4262-a81a-adf75dc1139e)

**Comment by bornova** [comment]
Hi @gagmeng,
Using bignumbers has its limitations unfortunately 😞 but I am not getting the same results on my end with default settings:

![image](https://github.com/bornova/numara-calculator/assets/35872220/9cdc7f46-e56c-4f4c-8a53-97ccea42c475)

Have you changed any settings? and can you please the share the Error message.

**Comment by gagmeng** [comment]
> Hi @gagmeng, Using bignumbers has its limitations unfortunately 😞 but I am not getting the same results on my end with default settings:
> 
> ![image](https://private-user-images.githubusercontent.com/35872220/299758561-9cdc7f46-e56c-4f4c-8a53-97ccea42c475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMjk5NzMsIm5iZiI6MTcwNjIyOTY3MywicGF0aCI6Ii8zNTg3MjIyMC8yOTk3NTg1NjEtOWNkYzdmNDYtZTU2Yy00ZjRjLThhNTMtOTdjY2VhNDJjNDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAwNDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YWQ4N2E4NzQ3MjI5ODRmNjQ4N2JmMzdmYzUyZjA3Y2JhZTAwY2IwOTFjMzYwNGYyOWZiYTYzNWUyYTMxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fqSL1YTG03_8abXs3SX1YsJGA9rwRKfGHSu1saxDNuk)
> 
> Have you changed any settings? and can you please the share the Error message.

![QQ截图20240126084343](https://github.com/bornova/numara-calculator/assets/13564117/9609b6ce-a3ef-4eed-b48a-5936987a9522)
![QQ截图20240126084519](https://github.com/bornova/numara-calculator/assets/13564117/814aa821-f849-4338-81b3-234de790be11)

**Comment by bornova** [comment]
Hi @gagmeng,
Sorry I was away for a few days.  Looks like you are the limitation of javascript when it comes to dealing with large numbers unfortunately. 😞   v4.4.3 does have a minor improvement to BigNumber but not sure if it will resolve your issues.  Since I rely on Math.js, I wouldn't be able to offer much help on this.
