### ISSUE TITLE
[feature request] - ability to subtract two dates

### ISSUE THREAD

**Issue by icaine** [bornova/numara-calculator#6]
It would be very useful if there is an ability to subtract two dates. Something like:
`2022-01-10 - 2022-01-5    |    5`

I realize that `2022-01-10` or `10/01/2022` is ambiguous (subtraction/division) so maybe use a special format like:
```
date(2022-01-10)
d2022-01-10
2022-01-10t
2022.10.10
10.01.2022
```
or maybe let the user to specify desired date(time) format in settings?
`YYYY-MM-DD_hh:mm:ss`

It would be also nice to have an ability to specify in what units to return the result:
`date(2022-01-10) - date(2022-01-5) in hours     |    120`

**Comment by bornova** [comment]
Hi @icaine,
Great suggestion!  I may be open to supporting something like `date(2022-01-10) - date(2022-01-5)` but doing `2022-01-10 or 10/01/2022` is not something I want take on at the moment due to the reason you mentioned: 
> I realize that 2022-01-10 or 10/01/2022 is ambiguous (subtraction/division)

That being said, Numara was never meant to be a date parser/calculator.  The reason I included some limited date calculations was I had a personal need to calculate lead times, such as _what day is 8 weeks from now_.  😄

**Comment by icaine** [comment]
I started using Numara with hope that it can do such things when i saw the examples with relative dates.. It just feels uncomplete if you can do `now - 1 week` but you can't choose any arbitrary date/time ;)

**Comment by bornova** [comment]
Hi @icaine,
I should mention that Numara uses Luxon to do the current available date calculations.  `luxon` is available in global scope so you can define your own custom functions as you wish.  For example, you can define the following function under 'User functions and units':
```javascript
dateDiff: (start, end, unit) => {
  const startDate = luxon.DateTime.fromISO(start)
  const endDate = luxon.DateTime.fromISO(end)
  const diff = endDate.diff(startDate, unit)

  return diff.toObject()[unit]
}
```
then in Numara, you can do: 
```
dateDiff('2022-02-07', '2022-02-14', 'days')    // 7
```

Hope this helps!
