### ISSUE TITLE
Undefined function DATE

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#84]
Version: 5.3.1
![image](https://github.com/user-attachments/assets/b6ea76a8-d8f3-4f87-abf4-8a812a1fab2d)

![image](https://github.com/user-attachments/assets/0134c995-d500-48a6-b284-cf56da36887d)

**Comment by bornova** [comment]
Hi @gagmeng,
Due to conflict with Mathjs functions and units, all [Formulajs](https://github.com/formulajs/formulajs) functions, such as DATE, now need to be prefixed with `xls.` since [v5.2.0](https://github.com/bornova/numara-calculator/releases/tag/v5.2.0)

Please try `xls.DATE(2024, 4, 30)`

Thanks!

**Comment by bornova** [comment]
That's correct.
